- hosts: all
  tasks:
           - package:
                   name: "httpd"
           
           - copy:
                   dest: "/var/www/html/index.html"
                   src: 'index.html'

           - replace:
                   path: "/etc/httpd/conf/httpd.conf"
                   regexp: "AllowOverride None"
                   replace: "AllowOverride Authconfig"

           - copy:
                   dest: "/var/www/html/.htaccess"
                   src: ".htaccess"

           - package:
                   name: 'python3'

           - pip:
                   name: "passlib"

           - htpasswd:
                   path: "/etc/www.passwd"
                   name: "pawan"
                   password: "rookie"

           - service:
                   name: 'httpd'
                   state: restarted
                   
           - firewalld:
           	    port:
           	    state:
           	    immediate: 	
                   

 
