# setting up load balancer and Reverse Proxy at the target node

- hosts: proxyserver
  tasks:
          - name: installing haproxy program
            package:
                    name: haproxy

        
          - name: configuring hapoxy 
            template:
                    dest: /etc/haproxy/haproxy.cfg
                    src: haproxy.cfg.j2

          - service:
                  name: haproxy
                  state: restarted


- hosts: webserver
  tasks:
        - name: installing httpd server
          package:
                  name: httpd

        - name: setting up website files
          copy:
               dest: /var/www/html/index.html
               content: SuccessFull


        - service:
                 name: httpd
                 state: started
