- hosts: all
  vars_prompt:
          - name: input
            private: no
            prompt: "Enter OS name:"
  tasks:
          - name: Configuing yum for Docker
            yum_repository:
                    name: dockerrpm
                    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
                    description: Dokcer yum repo
                    gpgcheck: no     

          - name: Installing docker program
            command: yum install docker-ce --nobest -y
            changed_when: false 
            args:
                 warn: no 

          - name: starting docker service
            service:
                    name: docker
                    state: started
                
          - name: Installing Docker SDK for Python4
            pip:
                   name: docker-py

          - name: pulling docker image
            docker_image:
                    name: centos:latest
                    source: pull 

          - name: launching a container
            docker_container:
                    name: "{{ input }}"
                    image: centos:latest
                    state: started
                    tty: true 
                    ports:
                            - 80  

      
